// Generated by https://quicktype.io

export interface IProducts {
    _id:         string;
    name:        string;
    price:       number;
    thumbnail:   string;
    description: string;
    stock:       number;
    __v:         number;
}
